### ISSUE TITLE
port,ip

### ISSUE THREAD

**Issue by protataetuk** [qwqdanchun/HVNC#1]
how to set port ip and change the listening port?

**Comment by qwqdanchun** [comment]
you can set in source code or use command line

---Original---
From: ***@***.***&gt;
Date: Mon, Sep 27, 2021 20:07 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [qwqdanchun/HVNC] port,ip (#1)




 
fow to set port ip and change the listening port?

**Comment by protataetuk** [comment]
thanks for your fast response .But where in the source code?

**Comment by qwqdanchun** [comment]
for example&nbsp;
client.exe 127.0.0.2


you can't change the port in command now



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 27, 2021 20:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [qwqdanchun/HVNC] port,ip (#1)




 
thanks for your fast response .But where in the command line?

**Comment by protataetuk** [comment]
thanks! But how to change the ports?

**Comment by qwqdanchun** [comment]
in source code&nbsp;



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 27, 2021 20:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [qwqdanchun/HVNC] port,ip (#1)




 
thanks! But how to change the ports?

**Comment by protataetuk** [comment]
> in source code&nbsp;
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Sep 27, 2021 20:29 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [qwqdanchun/HVNC] port,ip (#1) thanks! But how to change the ports? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

yeah but where?
![image](https://user-images.githubusercontent.com/78657954/134910237-b464e756-d16f-4889-8028-e76a0183efe7.png)

**Comment by protataetuk** [comment]
Oh i found the client port but i still cant find the listening one

**Comment by protataetuk** [comment]
oh find the other one.Thanks for your time!

**Comment by qwqdanchun** [comment]
https://github.com/qwqdanchun/HVNC/blob/1a15ec46bd6a5521b3adddb13937ed8251d3ad0a/Client/hiddenDesktop.cpp#L38




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qwqdanchun/HVNC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月27日(星期一) 晚上8:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qwqdanchun/HVNC] port,ip (#1)





  
in source code&nbsp;
 …
 ---Original--- From: @.&gt; Date: Mon, Sep 27, 2021 20:29 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [qwqdanchun/HVNC] port,ip (#1) thanks! But how to change the ports? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
yeah but where?
